client_config_backend: settings
client_config:
  client_id: 564191065145-iohrdoqruvmuuf4godsgau1f6b3nokkf.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install